name: Bug Report
description: Report a problem or unexpected behavior
title: "[Bug] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Describe the bug in detail...
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: How can we reproduce the issue?
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: OS, Browser, or any specific tool version
