name: Feature Request
description: Suggest an idea for the project
title: "[Feature] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the idea! Please describe it below.
  - type: textarea
    id: proposal
    attributes:
      label: Feature Proposal
      placeholder: What do you want to see?
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature needed?
      placeholder: What problem does it solve?
  - type: input
    id: related
    attributes:
      label: Related Issues or Discussions
      placeholder: #
